# Generated by Django 5.0.6 on 2024-06-08 22:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApplication', '0003_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phone', models.IntegerField(blank=True, null=True, unique=True)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_photos/')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApplication.categoria')),
                ('idVendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApplication.vendedor')),
            ],
            options={
                'ordering': ['name', 'unitPrice', 'stock', 'idCategoria', 'idVendedor'],
            },
        ),
    ]
