# Generated by Django 5.0.6 on 2024-06-08 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApplication', '0006_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['name']},
        ),
    ]
