# Generated by Django 5.0.6 on 2024-06-08 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApplication', '0007_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('idPublicacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('idComentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApplication.comentario')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApplication.producto')),
                ('idVendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApplication.vendedor')),
            ],
            options={
                'ordering': ['idProducto', 'idVendedor'],
            },
        ),
    ]
