# Generated by Django 5.0.6 on 2024-06-08 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApplication', '0009_carritocompras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompras',
            name='idProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApplication.producto'),
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
