# Generated by Django 5.0.6 on 2024-06-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApplication', '0010_alter_carritocompras_idproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompras',
            name='status',
            field=models.CharField(choices=[('empty', 'empty'), ('in_process', 'in process'), ('completed', 'completed')], default='empty', max_length=10),
        ),
    ]
