# Generated by Django 5.0.6 on 2024-06-08 23:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApplication', '0011_alter_carritocompras_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('idPedido', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApplication.producto')),
            ],
            options={
                'ordering': ['idProducto', 'amount', 'total'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payMethod', models.CharField(choices=[('credito', 'Tarjeta de Credito'), ('debito', 'Tarjeta de Debito'), ('paypal', 'Paypal'), ('otro', 'Otros')], default='credito', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApplication.usuario')),
                ('idVendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApplication.vendedor')),
                ('idProductoPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApplication.productopedido')),
            ],
            options={
                'ordering': ['idUsuario', 'idVendedor', 'idProductoPedido', 'total', 'date'],
            },
        ),
    ]
